[package]
name = "mscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = {git = "https://github.com/rrevenantt/antlr4rust", version = "0.3", branch = "v0.3"}
lazy_static = "1.4.0"